[[tests]]
submissions = ["expr.c"]  
make = [
  "cp $src/bst.h $src/read.c .", 
  "cc -Wall -o ./read read.c expr.c"
  ]

  [[tests.tests]]
  exe = "$test.sh"
  args = ["./read", "$tests.read"]

[[tests]]
submissions = ["expr.c"]  
make = [
  "cp $src/bst.h $src/fully.c .", 
  "cc -Wall -o ./fully fully.c expr.c"
  ]

  [[tests.tests]]
  exe = "$test.sh"
  args = ["./fully", "$tests.fully"]

[[tests]]
submissions = ["expr.c"]  
make = [
  "cp $src/bst.h $src/minimal.c .", 
  "cc -Wall -o ./minimal minimal.c expr.c"
  ]

  [[tests.tests]]
  exe = "$test.sh"
  args = ["./minimal", "$tests.minimal"]
