FROM proebstingcs/csc453_base:v1


COPY ./gradescope/run_autograder        /autograder
COPY ./gradescope/autograder.py         /autograder/source
COPY ./gradescope/utilities.py          /autograder/source
COPY ./gradescope/gradescope.json       /autograder/source
COPY ./foo          /autograder/source/foo

