"A1: First Programming Assignment" = "a1"
"A2: Histograms" = "a2"
"A3: Text" = "a3"
"A4: More Text" = "a4"
"A5: Columns" = "assignments/a5"
"A6: Bowling" = "assignments/a6"
"A7: Lists" = "assignments/a7"
"A8: BST" = "assignments/a8"
"A9: Expr" = "assignments/a9"
"A10: BCD" = "assignments/a10"
